### General

# The name of the application
spring.application.name=ej-auth-service
# The port fo the embedded server
server.port=${SERVER_PORT}

### OAuth2/OIDC related

# The secret key for the client application
client.secret=${CLIENT_SECRET}
# The URI to which the authorization server will redirect the user-agent after authentication
redirect.uri=${REDIRECT_URI}

### Logging

# Sets the logging level for Spring Security components to TRACE for detailed debugging.
logging.level.org.springframework.security=trace

### Datasource

# The JDBC URL for connecting to the PostgreSQL database
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
# The username for the database connection
spring.datasource.username=${DB_USERNAME}
# The password for the database connection
spring.datasource.password=${DB_PASSWORD}
# The fully qualified name of the JDBC driver
spring.datasource.driver-class-name=org.postgresql.Driver

### JPA & Hibernate

# Controls Hibernate's schema generation tool
spring.jpa.hibernate.ddl-auto=none
# Displays the SQL queries in the console.
spring.jpa.properties.hibernate.show_sql=false
# Formats the SQL queries displayed in the console.
spring.jpa.properties.hibernate.format_sql=true

### OpenAPI

# Version
springdoc.api-docs.version=OPENAPI_3_1
# Set custom path of the OpenAPI documentation in Json format
springdoc.api-docs.path=/api-docs
# Disable the springdoc-openapi endpoint
springdoc.api-docs.enabled=true
# The list of packages to scan (comma separated)
springdoc.packages-to-scan=com.ecommerce.auth.controller
# The list of paths to match (comma separated)
springdoc.paths-to-match=/auth/**

### Swagger UI

# Set custom path of the swagger-ui HTML documentation
springdoc.swagger-ui.path=/swagger-ui.html
# Disable the swagger-ui endpoint
springdoc.swagger-ui.enabled=true
# Controls whether the "Try it out" section should be enabled by default
springdoc.swagger-ui.tryItOutEnabled=true

### Redis

# The hostname of the Redis server (default: localhost)
spring.data.redis.host=${REDIS_HOST}
# The port of the Redis server (default: 6379)
spring.data.redis.port=${REDIS_PORT}
# Tells Spring Boot to use Redis as the application's cache manager.
spring.cache.type=redis
# The password for authentication with the Redis server
spring.data.redis.password=${REDIS_PASSWORD}