# General
spring.application.name=authservice
client.secret=${FRONTEND_CLIENT_SECRET}
redirect.uri=http://127.0.0.1:8080/login/oauth2/code/frontend

logging.level.org.springframework.security=trace

server.port=9000

spring.datasource.url=jdbc:postgresql://localhost:5432/e_database
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.hibernate.ddl-auto=validate

spring.flyway.url=${spring.datasource.url}
spring.flyway.user=${spring.datasource.username}
spring.flyway.password=${spring.datasource.password}

### OpenAPI

# Version
springdoc.api-docs.version=OPENAPI_3_1
# Set custom path of the OpenAPI documentation in Json format
springdoc.api-docs.path=/api-docs
# Disable the springdoc-openapi endpoint
springdoc.api-docs.enabled=true
# The list of packages to scan (comma separated)
springdoc.packages-to-scan=com.ecommerce.auth.controller
# The list of paths to match (comma separated)
springdoc.paths-to-match=/auth/**

### Swagger UI

# Set custom path of the swagger-ui HTML documentation
springdoc.swagger-ui.path=/swagger-ui.html
# Disable the swagger-ui endpoint
springdoc.swagger-ui.enabled=true
# Controls whether the "Try it out" section should be enabled by default
springdoc.swagger-ui.tryItOutEnabled=true
