spring.application.name=authservice
client.secret=${FRONTEND_CLIENT_SECRET}
redirect.uri=http://127.0.0.1:8080/login/oauth2/code/frontend

logging.level.org.springframework.security=trace

server.port=9000

spring.datasource.url=jdbc:postgresql://localhost:5432/e_database
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.hibernate.ddl-auto=validate

spring.flyway.url=${spring.datasource.url}
spring.flyway.user=${spring.datasource.username}
spring.flyway.password=${spring.datasource.password}
